FROM base_deneme:latest

RUN echo "" && \
    echo "" && \
    echo "------------------------------------" && \
    echo "------------------------------------" && \
    echo "        I'm base_ros_theia          " && \
    echo "------------------------------------" && \
    echo "------------------------------------" && \
    echo "" && \
    echo ""     
    
RUN echo $MYVAR
